### ISSUE TITLE
Php version problem

### ISSUE THREAD

**Issue by renekaigen** [Quirinus/Zippyshare-batch-download-PHP-cURL#4]
When I run the code , the error_log shows the next sentence:
Parse error: syntax error, unexpected '[' in /home/krowco1/public_html/kcash/zippi/zippy_batch_dl.php on line 176

**Comment by Quirinus** [comment]
Sorry for the late reply, I was on vacation.

You're probably using an older PHP version that doesn't support getting array members immediately from the result, if I understand correctly. (the [0] is messing things up) Please post your PHP version next time.

You'll have to split that line into more lines, like this:
`$algorithm_script_code = explode('document.getElementById(\'fimage\').href',$zippy_page);
$algorithm_script_code = end(explode('<script type="text/javascript">',$algorithm_script_code[0]));`

If this doesn't solve the problem, feel free to comment.

Edit: Oh, you already figured out it's a version problem. I overlooked the title. I added the note about my version in the readme, as to avoid these kind of reports. I don't want to support older versions, but thank you for your concern. I'm, however, willing to help anyone if they can't get it to work in older versions.
